name: Test Python application execution using Github Actions on Push Event
on: push
jobs:
    ExecutePython:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code from repository
              uses: actions/checkout@v3
            - name: Setup python environment for exeuting script 
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - run: python app.py
