name: Test Python application execution using Github Actions 
on: workflow_dispatch
jobs:
    ExecutePython:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - run: python app.py
